# Generated by Django 3.0.6 on 2020-06-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdid', models.CharField(max_length=6)),
                ('prdname', models.CharField(max_length=50)),
                ('prdcategory', models.CharField(choices=[('Vegetables', 'Vegetables'), ('Grocery', 'Grocery'), ('Stationary', 'Stationary'), ('Fruits', 'Fruits')], default='Vegetables', max_length=30)),
                ('prditemstypes', models.CharField(choices=[('Kg', 'kilogram'), ('Ltr', 'Litre'), ('pcs', 'Piece'), ('pack', 'Pack'), ('bundle', 'Bundle')], default='Kg', max_length=30)),
                ('prdimage', models.ImageField(upload_to='picturess')),
                ('prdstock', models.IntegerField()),
                ('prdqtytype', models.CharField(max_length=10)),
                ('prdprice', models.CharField(max_length=10)),
                ('prdoffer', models.BooleanField(default=False)),
                ('prdofferprice', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdid', models.CharField(max_length=6)),
                ('userid', models.CharField(max_length=50)),
                ('prdname', models.CharField(max_length=50)),
                ('prdimage', models.CharField(max_length=50)),
                ('prdprice', models.IntegerField(default=0)),
                ('qty', models.IntegerField(default=1)),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.Products')),
            ],
        ),
    ]
